version: '3.8'

networks:
  commerce-network:
    driver: bridge

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    networks:
      - commerce-network

  user-service:
    build:
      context: .
      dockerfile: MiniCommerce.UserService/Dockerfile
    container_name: user-service
    ports:
      - "5001:8080"
    environment:
      - Kafka__BootstrapServers=kafka:29092
    volumes:
      - ./DockerData/Users:/app/Database
    depends_on:
      - kafka
    networks:
      - commerce-network

  product-service:
    build:
      context: .
      dockerfile: MiniCommerce.ProductService/Dockerfile
    container_name: product-service
    ports:
      - "5002:8080"
    environment:
      - Kafka__BootstrapServers=kafka:29092
    volumes:
      - ./DockerData/Products:/app/Database
    depends_on:
      - kafka
    networks:
      - commerce-network

  order-service:
    build:
      context: .
      dockerfile: MiniCommerce.OrderService/Dockerfile
    container_name: order-service
    ports:
      - "5003:8080"
    environment:
      - Kafka__BootstrapServers=kafka:29092
      - ProductServiceUrl=http://product-service:8080
    volumes:
      - ./DockerData/Orders:/app/Database
    depends_on:
      - kafka
      - product-service
    networks:
      - commerce-network